### ISSUE TITLE
Please, fix my name :-)

### ISSUE THREAD

**Issue by iguerNL** [agata-borkowska/dissertation#1]
Iguernala (Abstract)
Igernelala (Related Works > Methods for verifying provers)
Igeurnelala (Project Aims > Methodology)

Should be ```Iguernlala```

**Comment by agata-borkowska-clark** [comment]
@OCamlPro-Iguernlala I am terribly sorry about it, and thank you for pointing it out. It is fixed now. Please note that your name is listed as "Iguernelala" in Springer: https://link.springer.com/chapter/10.1007/978-3-662-43652-3_27

**Comment by iguerNL** [comment]
This is another administrative fix I made rencently ...
